# 03-knot-config-cat-secondary.yaml
# ---
# CONFIGURATION FOR A SECONDARY CATALOG SITE
# ---
apiVersion: v1
kind: ConfigMap
metadata:
  # This name is REQUIRED. The StatefulSet is configured to look for 'knot-config'.
  name: knot-config
  namespace: dns-system
data:
  knot.conf: |
    # /etc/knot/knot.conf - For a Secondary Catalog Site
    server:
      listen: [ 0.0.0.0@53, '::'@53 ]
      listen-quic: [ 0.0.0.0@853, '::'@853 ]
      tls-cert-file: /etc/knot/pki/tls.crt
      tls-key-file: /etc/knot/pki/tls.key

    log:
      - target: syslog
        any: info

    key:
      - id: xfr-key
        algorithm: hmac-sha256
        secret-file: /etc/knot/tsig/tsig-secret # Mounted from Secret

    # Add all sites in the mesh here for communication using their public DNS names.
    remote:
      - id: catalog-primary-remote
        address: site-primary.dns.internal@853 # !!! CHANGE THIS to the site's FQDN !!!
        key: xfr-key
        quic: on
      - id: catalog-secondary-remote
        address: site-secondary.dns.internal@853 # !!! CHANGE THIS to the site's FQDN !!!
        key: xfr-key
        quic: on
      - id: standard-1-remote
        address: site-standard-1.dns.internal@853 # !!! CHANGE THIS to the site's FQDN !!!
        key: xfr-key
        quic: on

    acl:
      - id: transfer-acl
        remote: [catalog-primary-remote, catalog-secondary-remote, standard-1-remote]
        action: transfer
      - id: notify-acl
        remote: [catalog-primary-remote, catalog-secondary-remote, standard-1-remote]
        action: notify

    policy:
      - id: default-signing-policy
        algorithm: ecdsap256sha256
        zsk-lifetime: 2592000
        ksk-lifetime: 31536000

    template:
      - id: primary-template
        storage: /var/lib/knot/zones/
        # Notify all OTHER sites.
        notify: [catalog-primary-remote, standard-1-remote]
        acl: [transfer-acl, notify-acl]
        soa-expire: 3628800
        journal-content: all
        dnssec-signing: on
        dnssec-policy: default-signing-policy
      - id: secondary-template
        storage: /var/lib/knot/zones/
        master: [catalog-primary-remote, catalog-secondary-remote, standard-1-remote]
        acl: notify-acl
        soa-expire: 3628800
        journal-content: all

    zone:
      # This site is PRIMARY for its own zone.
      # !!! CHANGE THIS to your site's unique domain !!!
      - domain: catalog-secondary.internal.dns
        template: primary-template

      # This site INTERPRETS the catalog to configure its member zones.
      # It will try the primary catalog site first, then itself as a backup master.
      - domain: catalog.internal.dns
        master: [catalog-primary-remote, catalog-secondary-remote]
        catalog-role: interpret
        catalog-template: secondary-template

      # This site is a SECONDARY for the mesh's "address book" zone.
      - domain: dns.internal
        master: catalog-primary-remote
        template: secondary-template
