# 04-dns-internal-zone-configmap.yaml
# This manifest contains the "address book" and "card catalog" zone for the mesh.
# It maps FQDNs to IPs (A records) and Zone Names to FQDNs (TXT records).
#!!! THIS SHOULD ONLY BE DEPLOYED TO THE PRIMARY CATALOG SITE !!!
apiVersion: v1
kind: ConfigMap
metadata:
  name: knot-dns-internal-zone
  namespace: dns-system
data:
  dns.internal.zone: |
    ; Address book for the internal DNS mesh
    $ORIGIN dns.internal.
    @       3600    IN      SOA     ns1.catalog-primary.internal.dns. admin.catalog-primary.internal.dns. (
                                    2024080601 ; Serial (YYYYMMDDnn)
                                    3600       ; Refresh
                                    600        ; Retry
                                    3628800    ; Expire (42 days)
                                    3600       ; Minimum TTL
                                    )
            3600    IN      NS      ns1.catalog-primary.internal.dns.

    ; --- A Records for Each Site's FQDN ("Address Book") ---
    ; These records map the FQDNs to the actual external IP addresses of the sites.
    site-primary            3600    IN      A       192.0.2.1   ; !!! CHANGE THIS to the site's external IP !!!
    site-secondary          3600    IN      A       198.51.100.2; !!! CHANGE THIS to the site's external IP !!!
    site-standard-1         3600    IN      A       203.0.113.3 ; !!! CHANGE THIS to the site's external IP !!!

    ; --- TXT Records Mapping Zone Base Name to Primary Server FQDN ("Card Catalog") ---
    ; This tells the reconciler which server is the master for which zone.
    catalog-primary         3600    IN      TXT     "site-primary.dns.internal"
    catalog-secondary       3600    IN      TXT     "site-secondary.dns.internal"
    standard-1              3600    IN      TXT     "site-standard-1.dns.internal"